// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'directConnect': string;
  'torrent': string;
  'usenet': string;
}
export const cssExports: CssExports;
export default cssExports;
